# Generated by Django 4.2.7 on 2023-11-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='name_url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
